swagger: "2.0"
info:
  title: NetZero Academy Courses
  description: Lists upcoming courses for energy consultants. Kurse für Energieberater.
  version: 1.0.0
host: hook.eu1.make.com/xztbbwwtmuvy0kppfryfd0rwrkfh6sc6
basePath: /
schemes:
  - https
paths:
  /:
    get:
      summary: Returns a list of upcoming courses.
      description: Liste mit Daten von zukünftigen Kursen für Energieberater.
      produces:
        - application/json
      responses:
        200:
          description: OK
