: swagger: "2.0"
info:
  title: NetZero Academy Courses
  description: Lists upcoming courses for energy consultants. 
  version: 1.0.0
host: hook.eu1.make.com
basePath: /
schemes:
  - https
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
security:
  - ApiKeyAuth: []
paths:
  /xztbbwwtmuvy0kppfryfd0rwrkfh6sc6:
    get:
      summary: Retrieve list of upcoming courses
      description: Retrieve a list of upcoming courses with start and end date details and a link to the course description in the web page.
      operationId: getUpcomingCourses
      produces:
        - application/json
      responses:
        200:
          description: A list of courses
          schema:
            type: array
            items:
              type: object
              properties:
                Title:
                  type: string
                  example: "Energieberatung Vertiefungskurs WG 05.08. - 09.08.2024"
                Description:
                  type: string
                  example: "Im Kurs Energieberater Wohngebäude eignest Du Dir umfassende Kenntnisse in allen Aspekten energetischer Sanierungen für Planung, Ausführung und Kontrolle an. Du erhältst Einblicke in Baubetreuung, Bauüberwachung und Qualitätssicherung.\n\nNach dem Kurs bist Du Energieberater:in für Wohngebäude\n"
                Start:
                  type: string
                  format: date
                  example: 2024-08-05
                End:
                  type: string
                  format: date
                  example: 2024-08-09
                URL:
                  type: string
                  format: uri
                  example: "https://www.netzeroacademy.de/energieberater-wohngebauede"
      tags:
        - name: Courses
          description: Lists upcoming courses 
